apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deploy.yaml
  - manifests/hpa.yaml
configMapGenerator:
  - envs:
      - runner.env
    name: runner-k8s-config
    namespace: github
images:
  - name: gcr.io/PROJECT_ID/runner
    newName: gcr.io/PROJECT_ID/runner
    newTag: latest
