apiVersion: apps/v1
kind: Deployment
metadata:
    name: runner-deployment
    namespace: github
spec:
    selector:
        matchLabels:
            app: runner
    replicas: 2
    template:
        metadata:
            labels:
                app: runner
        spec:
            serviceAccountName: gke-runner-sa
            automountServiceAccountToken: true
            containers:
                - name: runner
                  image: gcr.io/PROJECT_ID/runner:latest
                  envFrom:
                      - configMapRef:
                            name: runner-k8s-config
                      - secretRef:
                            name: runner-k8s-secret
                  lifecycle:
                      preStop:
                          exec:
                              command:
                                  [
                                      '/bin/bash',
                                      '-c',
                                      'RUNNER_ALLOW_RUNASROOT=1 ./config.sh remove --token $ACTION_TOKEN',
                                  ]
                  resources:
                      requests:
                          memory: '256Mi'
                          cpu: '500m'
                      limits:
                          memory: '512Mi'
                          cpu: '1'
