apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: runner-deployment-hpa
  namespace: github
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: runner-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
