name: Deploy Self Hosted Runners
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build and Deploy Image
        run: gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/runner:${{ github.sha }}
      - id: get-credentials
        name: Get Credentials
        uses: GoogleCloudPlatform/github-actions/get-gke-credentials@master
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: us-central1-a
      - id: get-pods
        run: kubectl get pods
