name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build and Deploy Image
        run: gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/runner:${{ github.sha }}
