name: Deploy Self Hosted Runners
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
            - uses: actions/checkout@v2
            - uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ secrets.PROJECT_ID }}
                  service_account_key: ${{ secrets.GCP_SA_KEY }}
                  export_default_credentials: true
            - name: Build and Deploy Image
              run: gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/runner:${{ github.sha }}
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@master
            - uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: ${{ secrets.PROJECT_ID }}
                  service_account_key: ${{ secrets.GCP_SA_KEY }}
                  export_default_credentials: true
            - id: get-credentials
              name: Get Credentials
              uses: google-github-actions/get-gke-credentials@main
              with:
                  cluster_name: ${{ secrets.CLUSTER_NAME }}
                  location: us-central1-a
            - name: Make envfile
              uses: SpicyPizza/create-envfile@v1
              with:
                  envkey_ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
                  envkey_ACTION_URL: ${{ secrets.ACTION_URL }}
                  file_name: runner.env
            - name: Setup Kustomize
              uses: imranismail/setup-kustomize@v1
              with:
                  kustomize-version: '3.9.2'
            - name: Update image
              run: kustomize edit set image gcr.io/PROJECT_ID/runner:latest=gcr.io/${{ secrets.PROJECT_ID }}/runner:${{ github.sha }}
            - name: Build
              run: kustomize build . | kubectl apply -f -
